version: "3"
services:
    opensearch:
        image: "opensearchproject/opensearch:latest"
        environment:
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "discovery.type=single-node"
        ports:
            - "9200:9200"
        volumes:
            - opensearch_data:/usr/share/opensearch/data

    dashboards:
        image: "opensearchproject/opensearch-dashboards:latest"
        ports:
            - "5601:5601"
        environment:
            OPENSEARCH_HOSTS: '["https://opensearch:9200"]'

    logstash:
        image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2
        volumes:            
            - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

    filebeat:
        user: root
        image: "docker.elastic.co/beats/filebeat:7.2.0"        
        volumes:
            - ./logs/:/var/log/
            - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro

volumes:
    opensearch_data:
